# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
  
- task: Docker@2
  inputs:
    containerRegistry: 'ACR Registry'
    repository: 'atharvatest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'SST Cluster'
    manifests: 'httpd.yaml'
    imagePullSecrets: 'regcred'

# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Kubernetes Service Connection'
#     kubernetesServiceEndpoint: 'SST Cluster'
#     command: 'set'
#     arguments: 'image sts httpd mongo=atharvatest:$(Build.BuildId)'
#     secretType: 'dockerRegistry'
#     containerRegistryType: 'Azure Container Registry'